_format_version: "2.1"

services:
  - name: backend
    url: http://backend:5000
    routes:
      - name: backend-service
        paths: 
          - /backendproxy

  - name: frontend
    url: http://frontend:4200
    routes:
      - name: frontend-service
        paths: 
          - /

plugins:
  - name: cors
    service: frontend
    config: 
      origins:
        - http://mockbin.com
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false
          
